# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "demo-aws-terraform-state-backend"
    encrypt = true
    key     = "project/ec2/terraform.tfstate"
    region  = "us-east-1"
  }
}
